/* Generated by Together */

package uk.org.toot.swingui.audioui.serverui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;

public class AudioServerUIButton extends JButton implements ActionListener
{
    private JFrame serverFrame;

    public AudioServerUIButton(JComponent serverUI) {
        super("Server");
		if ( serverUI == null ) {
            setEnabled(false);
            return;
        }

		serverFrame = new JFrame("Audio Server");
		serverFrame.setAlwaysOnTop(true);
		serverFrame.setContentPane(serverUI);
		serverFrame.pack();
		addActionListener(this);
    }

    public void actionPerformed(ActionEvent ae) {
		if ( serverFrame != null) {
			serverFrame.setVisible(true);
		}
    }
}
