/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import uk.org.toot.midi.sequence.MidiTrack;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import uk.org.toot.swingui.midiui.sequenceui.SequenceTimeView;
import uk.org.toot.swingui.midiui.sequenceui.SequenceView;

abstract public class AbstractPitchView extends SequenceTimeView {
    public AbstractPitchView(Viewer sequence) {
        super(sequence);
    }

    protected JPopupMenu createPopupMenu() {
        return new PitchPopup();
    }

    protected boolean isValid(MidiTrack track) {
        return !track.isDrumTrack();
	}

    public class PitchPopup extends SequenceView.TimePopup {
        private JMenu pitchMenu;

        // constructor
        public PitchPopup() {
            super();
            pitchMenu = createPitchMenu();
            add(pitchMenu);
        }

        protected JMenu createPitchMenu() {
            JMenu menu = new JMenu("Pitch");
            menu.add(new JMenuItem("Zoom In"));
            menu.add(new JMenuItem("Zoom Out"));
            return menu;
        }
    }
}
