/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import javax.swing.JScrollPane;

public class DomainSplitView extends SplitView {

    public DomainSplitView(ViewScrollPane top, ViewScrollPane bottom) {
        super(top, bottom);
    }

    public SequenceTimeView getTopView() {
        JScrollPane scrollPane = getTopScrollPane();
        return (SequenceTimeView)(scrollPane.getViewport().getView());
    }

    public SequenceTimeView getBottomView() {
        JScrollPane scrollPane = getBottomScrollPane();
        return (SequenceTimeView)(scrollPane.getViewport().getView());
    }

    public ViewScrollPane getTopScrollPane() {
        return (ViewScrollPane)getTopComponent();
    }

    public ViewScrollPane getBottomScrollPane() {
        return (ViewScrollPane)getBottomComponent();
    }

    public void repaintPositionCursor(long pos) {
        // cheap and cheerful composition
        SequenceTimeView view;
        view = getTopView();
        if ( view.isVisible() )
	        view.repaintPositionCursor(pos);
        view = getBottomView();
        if ( view.isVisible() )
	        view.repaintPositionCursor(pos);
    }

    public void setStartPosition(int x) {
        // cheap and cheerful composition
        setStartPosition((JScrollPane)getTopComponent(), x);
        setStartPosition((JScrollPane)getBottomComponent(), x);
    }

    protected void setStartPosition(JScrollPane scrollPane, int x) {
        java.awt.Point topleft = scrollPane.getViewport().getViewPosition() ;
        topleft.x = x;
        scrollPane.getViewport().setViewPosition(topleft) ;
    }

    // override JSplitPane
    public boolean isValidateRoot() { return false; }
}
