/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import javax.swing.JPanel;
import javax.swing.JComponent;
import java.awt.BorderLayout;
import uk.org.toot.midi.core.MidiSystem;
import uk.org.toot.midi.sequence.SequenceHistory;

abstract public class Editor extends Viewer
{
    public Editor(OpenSequenceUI openSeqUI, MidiSystem rack) {
        super(openSeqUI, rack);
        createEditToolBar();
        // create inner panel so we can have another toolbar
        JPanel innerPane = new JPanel(new BorderLayout());
        innerPane.add(getEditToolBar(), BorderLayout.WEST); // was infoBar
        innerPane.add(createContent(), BorderLayout.CENTER);
        add(innerPane, BorderLayout.CENTER);
    }

    abstract protected JComponent createContent();

    protected void createEditToolBar() {
        tools = new EditToolBar(this, getHistory());
    }

    public EditToolBar getEditToolBar() {
        return tools;
    }

    public ToolPalette getToolPalette() {
        return tools.getToolPalette();
    }

    public SequenceHistory getHistory() {
        return getSequence().getHistory();
    }

    public boolean canTruncate() { return false; }

    public void setCurrentTool(PaletteTool tool) {
    }

    public int getDefaultNote(SequenceView view, int x, int y) {
        return view.note(x, y);
    }

    public int getDefaultVelocity(SequenceView view) {
        return view.getDefaultVelocity();
    }

    /**
     * @supplierCardinality 1
     * @link aggregationByValue 
     */
    protected EditToolBar tools;
}
