/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import javax.swing.JToolBar;
import uk.org.toot.midi.sequence.SequenceHistory;

public class EditToolBar extends JToolBar{
    /**
     * @supplierCardinality 1
     * @link aggregationByValue 
     */
    private ToolPalette toolPalette;

    public EditToolBar(Editor editor, SequenceHistory history) {
        super("Editing Tools");
        setOrientation(VERTICAL);
    	add(new HistoryToolBar(history));
    	add(new SelectionToolBar(editor));
    	add(toolPalette = new ToolPalette(editor));
    }

    public ToolPalette getToolPalette() { return toolPalette; }
}
