/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import java.awt.event.MouseEvent;
import java.awt.Point;
import uk.org.toot.midi.sequence.MidiTrack;
import uk.org.toot.midi.sequence.edit.TrackSelection;
import uk.org.toot.midi.sequence.edit.SequenceSelection;
import uk.org.toot.midi.sequence.edit.Cut;

public class EraseTool extends PaletteTool
{
    public EraseTool(Editor editor) { super("Erase", "Erase16", "Erase32", new Point(6, 9), editor); }

    public void mouseDragged(MouseEvent e) {
        if ( press == null ) return;
        if ( e.getSource() != press.getSource() ) return;
        super.mouseDragged(e); // ensure wasDragged is valid
		drawSelectionArea(e);
    }

    public void mouseReleased(MouseEvent e) {
        if ( press == null ) return;
        if ( e.getSource() != press.getSource() ) {
            press = null;
            return;
        }
        SequenceView view = (SequenceView)e.getSource();
        if ( wasDragged() ) { // erase the latest selection
	        MidiTrack track = view.getTopTrack();
        	selection = new TrackSelection(track, getMatches(e));
        }
        edit(new Cut(getSelection()));
        // force a viewer update if selection is persistent one
        // !!! needs to be done per execute !!! !!!
        if ( getSelection() instanceof SequenceSelection ) {
        	view.getSelection().clear();
        }
        press = null;
    }
}
