/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

//import java.beans.PropertyChangeListener;
import java.awt.event.ActionEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
//import java.awt.BorderLayout;
//import java.awt.FlowLayout;
//import java.awt.Color;
//import java.awt.Component;
import javax.swing.JButton;
import uk.org.toot.midi.sequence.SequenceHistory;
import uk.org.toot.swingui.miscui.TootBar;

/**
 * History Tools
 */
class HistoryToolBar extends TootBar
{
    private final static String UNDO = "Undo";
    private final static String REDO = "Redo";
    private final static String HISTORY = "History";
    private JButton undoB;
    private JButton redoB;
    private JButton historyB;

    private SequenceHistory history;

    public HistoryToolBar(SequenceHistory history) {
        super("History Tools");
        this.history = history;
        setOrientation(TootBar.VERTICAL); // !!!
        undoB = makeButton("general/Undo16", UNDO, UNDO, UNDO, false);
        add(undoB);
        redoB = makeButton("general/Redo16", REDO, REDO, REDO, false);
        add(redoB);
        historyB = makeButton("general/History16", HISTORY, HISTORY, HISTORY, true);
//        add(historyB);

        history.getChangeSupport().addChangeListener(
            new ChangeListener() {
	            public void stateChanged(ChangeEvent chev) {
                	updateButtons();
            	}
        	});
    }

    protected void updateButtons() {
        undoB.setEnabled(history.canUndo());
        undoB.setToolTipText(history.getUndoPresentationName());
        redoB.setEnabled(history.canRedo());
        redoB.setToolTipText(history.getRedoPresentationName());
        historyB.setEnabled(history.canUndoOrRedo());
    }

    public void actionPerformed(ActionEvent e) {
   	    String cmd = e.getActionCommand();

        if ( UNDO.equals(cmd) ) {
//            System.out.println(history.getUndoPresentationName()+"...");
            history.undo();
        }
        else if ( REDO.equals(cmd) ) {
//            System.out.println(history.getRedoPresentationName()+"...");
            history.redo();
        }
        else if ( HISTORY.equals(cmd) ) {
            /* !!! display HistoryView */
        }
    }
}


