/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import java.io.File;
import javax.swing.filechooser.FileFilter;

/* TODO:
	accept .MID files!!!
 */
public class MidiFileFilter extends FileFilter
{
    public boolean accept(File f)
    {
        if (f.isDirectory()) {
            return true;
        }

        String filename = f.getPath();
        String ext = filename.substring(filename.length()-4) ;
        if ( ext.equals(".mid") || ext.equals(".MID") )
            return true ;

        return false;
    }

    public String getDescription()
    {
        return "MIDI Files";
    }
}
