/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

public class NormalisedDualPoint
{
    public int left;
    public int top;
    public int right;
    public int bottom;

    public NormalisedDualPoint(int x1, int y1, int x2, int y2) {
        left   = x1 < x2 ? x1 : x2;
        top    = y1 < y2 ? y1 : y2;
        right  = x1 < x2 ? x2 : x1;
        bottom = y1 < y2 ? y2 : y1;
    }
}


