/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import java.awt.Component;
import javax.swing.JScrollPane;

public class ScrollView extends JScrollPane
{
    public ScrollView(Component component) {
        super(component);
        getViewport().setBackground(getBackground());
    }
}
