/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import uk.org.toot.midi.sequence.MidiSequence;
import uk.org.toot.midi.sequence.MidiTrack;
import uk.org.toot.swingui.midiui.sequenceui.TrackEditor;
import javax.swing.JComboBox;

public class SequenceEditor extends TrackEditor
{
    protected final MidiSequence sequence ;
//    protected JComboBox trackCB ;
    protected JComboBox markerCB ;

    public SequenceEditor(MidiSequence sequence)
    {
        this(sequence, 0) ; // display track 0
    }

    public SequenceEditor(MidiSequence sequence, int trk)
    {
        super(sequence.getMidiTrack(trk));
        this.sequence = sequence ;
        extendToolBar();
        extendInfoBar();
    }


    /**
     * override TrackEditor to provide sequence bar.beat.tick position string
     */
    protected String getPosition(long tick) {
        return sequence.getPosition(tick).toString();
    }

    protected void extendToolBar() {
        toolBar.addSeparator();
        TrackLabel trackLabel = new TrackLabel(sequence, sequence.getMidiTrack(0)) {
            public void setSelectedTrack(MidiTrack track) {
                super.setSelectedTrack(track);
                setTrack(track);
            }
        };
        toolBar.add(trackLabel);
    }

    protected void extendInfoBar() {
        markerCB = new MarkerCombo(sequence) ;
        infoBar.add(markerCB);
    }
}
