/* Generated by TooT */

package uk.org.toot.swingui.midiui.sequenceui;

import javax.swing.JScrollPane;
import javax.swing.JComponent;
import uk.org.toot.swingui.midiui.sequenceui.SequenceTimeView;

public class TimeScrollPane extends JScrollPane
{
    protected SequenceTimeView view;
    protected SequenceTimeView.TimeHeader timeHeader;
    protected JComponent yHeader;
    // Add listener so the popup menu can come up.

/*    public void setSequencer(MidiSequencer sequencer) {
        this.sequencer = sequencer ;
        view.setSequencer(sequencer) ;
    } */

    public void setTicksPerPixel(float tpp) {
        view.setTicksPerPixel(tpp) ;
        if ( timeHeader != null ) {
        	timeHeader.setSize(timeHeader.getPreferredSize());
        	timeHeader.repaint();
        }
    }

    public void zoomInY() {
        view.setPixelsPerY(view.getPixelsPerY()+1) ;
        yHeader.setSize(yHeader.getPreferredSize());
        yHeader.repaint();
        view.repaint();
    }

    public void zoomOutY() {
        view.setPixelsPerY(view.getPixelsPerY()-1) ;
//        pitchHeader.setHeight(view.getHeight());
        yHeader.setSize(yHeader.getPreferredSize());
        yHeader.repaint();
        view.repaint();
    }

    public SequenceTimeView getView()	{
        return view;
    }
}
