/* Generated by TooT */

package uk.org.toot.pitch;

/**
 * C-1 = 0
 * C0 = 12
 * C1 = 24
 * C2 = 36
 * C4 (middle-C) = 60 (arbitrary MMA definition)
 */
public class Pitch extends PitchClass
{
    private Pitch() {
        // to prevent instantiation
    }

    static public String name(int value) {
        return PitchClass.name(value)+((int)(value/12)-1);
    }

/*    public static int value(String name) {
        return PitchClass.value(name)+...;
    } */

    public static int value(String name, int register) {
        return value(PitchClass.value(name), register);
    }

    public static int value(int pitchClass, int register) {
        return pitchClass+(12*(register+1));
    }
}
