/* Generated by TooT */

package uk.org.toot.midi.sequence;

import javax.sound.midi.MidiEvent;
import uk.org.toot.midi.message.ChannelMsg;

public class MidiNote implements Cloneable {
    public MidiEvent on;
    public MidiEvent off;

    public MidiNote(MidiEvent on, MidiEvent off) {
        this.on = on;
        this.off = off;
    }

    public int getNoteValue() {
        return ChannelMsg.getData1(on.getMessage());
    }

    public int getVelocity() {
        return ChannelMsg.getData2(on.getMessage());
    }

    public boolean equals(Object o) {
        if (!(o instanceof MidiNote)) return false;
        MidiNote n = (MidiNote)o;
        // !!! is this what fecks Move/Copy
        return on.equals(n.on) && off.equals(n.off);
    }

    public Object clone() {
        try {
            MidiNote cloned = (MidiNote)super.clone();
            // don't deep copy events (and can't anyway)
//            cloned.on = new MidiEvent((MidiMessage)on.getMessage().clone(), on.getTick());
//            cloned.off = new MidiEvent((MidiMessage)off.getMessage().clone(), off.getTick());
            return cloned;
        } catch (CloneNotSupportedException cnse) {
            cnse.printStackTrace();
        }
        return null;
    }
}
