/* Generated by TooT */

package uk.org.toot.midi.sequence;

import javax.sound.midi.MidiEvent;
import uk.org.toot.midi.message.MetaMsg;

/** NameEvent class */
public class NameEvent {
    protected final MidiEvent event;
    protected String name = null;
    protected long tick = -1;

    public NameEvent(MidiEvent event) {
        this.event = event;
    }

    /** Construct a fake name event */
    public NameEvent(String name, long tick) {
        this.name = name;
        this.tick = tick;
        this.event = null;
    }

    public String getName() {
        if (name != null) return name;
        return MetaMsg.getString(event.getMessage());
    }

    public long getTick() {
        if (tick >= 0) return tick;
        return event.getTick();
    }
}
