/* Generated by TooT */

package uk.org.toot.midi.sequence;

import uk.org.toot.misc.History;

public class SequenceHistory extends History {
    /** @supplierCardinality 1 */
    private MidiSequence sequence;

    public SequenceHistory(MidiSequence sequence) {
        this.sequence = sequence;
    }

    protected void fireChanged() {
        super.fireChanged();
        sequence.fireChanged();
    }
}
