/* Generated by TooT */

package uk.org.toot.pitch;

/**
 * A Scale is a list of intervals.
 * Melodies are derived from a scale.
 * Chords are derived from the modes of a scale.
 * @author st
 *
 */
public class Scale 
{
    private String name ;
    private int[] intervals ;

    /**
     * Constructor
     */
    public Scale(String name, int[] intervals) {
        this.name = name ;
        this.intervals = intervals ;
    }

    public String name() { return name ; }

    public int length() { return intervals.length ; }

    public int interval(int degree) { 
    	return ChordMode.interval(intervals, degree) ; 
    }

    public int interval(int degree1, int degree2) {
    	return ChordMode.interval(intervals, degree1, degree2);
    }
    
    public String getName() { return name; }

    public int[] getIntervals() {
    	return intervals;
    }
    
    /**
     * Derive the Chord Mode for the degree
     * @param degree
     * @return
     */
    public int[] getChordMode(int degree) {
    	int[] intervals = new int[length()];
    	for ( int i = 1; i < length(); i++ ) {
    		intervals[i] = intervals[i-1] + interval(degree+i-1, degree+i);
    	}
    	return intervals;
    }
    
    /**
     * @return true if interval is diatonic from this degree, false otherwise
     */
    public boolean hasInterval(int degree, int val) {
        int i2 = (interval(degree)+val)%12;
        for ( int i = 0; i < length(); i++ ) {
			if ( i2 == interval(i) ) return true;
        }
        return false;
    }
}
