/* Generated by Together */

package uk.org.toot.audio.core;

/**
 * A simple AudioProcess with empty open and close implementations
 */
abstract public class SimpleAudioProcess implements AudioProcess
{
    public void open() {}

    public void close() {}
}
