/* Generated by Together */

package uk.org.toot.audio.delay;

import uk.org.toot.control.ControlLaw;
import uk.org.toot.control.FloatControl;
import uk.org.toot.control.LinearLaw;
import java.awt.Color;

import static uk.org.toot.localisation.Localisation.*;

public class StereoModulatedDelayControls extends ModulatedDelayControls implements StereoModulatedDelayVariables
{
    private static final ControlLaw phaseLaw = new LinearLaw(0f, 180f, "degrees");
    private FloatControl phaseControl;

    public StereoModulatedDelayControls() {
        super(DelayIds.STEREO_MODULATED_DELAY_ID, getString("Stereo.Modulated.Delay"));
    }

    public float getPhaseRadians() {
        return (float)(phaseControl.getValue() * Math.PI / 90);
    }

    protected ControlColumn createControlColumn1() {
        phaseControl = new FloatControl(PHASE_ID, getString("Phase"), phaseLaw, 1f, 0f);
        phaseControl.setInsertColor(Color.BLUE.darker());
        ControlColumn cc = super.createControlColumn1();
		cc.add(phaseControl);
        return cc;
    }
}
