/* Generated by Together */

package uk.org.toot.audio.server;

import uk.org.toot.audio.server.spi.AudioServerServiceProvider;
import uk.org.toot.audio.id.ProviderId;

public class TootAudioServerServiceProvider extends AudioServerServiceProvider
{
    public TootAudioServerServiceProvider() {
        super(ProviderId.TOOT_PROVIDER_ID, "Toot Software", "Toot Audio Servers", "0.1");
        add(JavaSoundAudioServer.class, "JavaSound (stereo)", "default stereo", "0.4");
        // if ASIO available add an ASIO provider
    }
}
