/* Generated by TooT */

package uk.org.toot.midi.sequence.compat;

import uk.org.toot.midi.sequence.MidiSequence;

/* Support Cubase MIDI files
 * in VST 5 the following problems appear to have been identified:
 * a) Tempo incorrectly set to 120bpm (can probably be found in .ALL)
 * b) Program Change absent (has been found in .ALL)
 * c) SMPTE Offset absent (2 bar default)
 */

public class Cubase {
    static public boolean created(MidiSequence sequence) {
        // if tempo is 120bpm
        if (sequence.getBeatsPerMinute() != 120.0f) return false;
        // and SMPT Offset is absent
        // and Program Changes are absent
        return true; // !! for early testing only
    }

    static public MidiSequence fix(MidiSequence sequence) {
        // change tempo to 128bpm?
        // add 2 bar SMPT Offset
        // add Program Changes
        return sequence;
    }
}
