/* Generated by TooT */

package uk.org.toot.midi.sequence.edit;

import uk.org.toot.misc.UndoableCommand;

public class Copy implements UndoableCommand
{
    /** @supplierCardinality 1 */
    private Copyable selection;

    public Copy(Copyable sel, long ticks, int semitones) {
        this.selection = (Copyable)sel.deepCopy();
        selection.move(ticks, semitones);
    }

    public String getName() { return "Copy"; }

    public boolean execute() { return selection.paste(); }

    public boolean unexecute() { return selection.cut(); }

	public boolean isStructural() {
		return false;
	}
}
