/* Generated by TooT */

package uk.org.toot.midi.sequence.edit;

abstract public class CutPasteCommand
{
	private boolean structural = false;
	
    public CutPasteCommand(CutPasteable selection) {
//    	throws CloneNotSupportedException {
    	try {
    		this.selection = (CutPasteable)selection.clone();
    	} catch ( CloneNotSupportedException cnse ) {
    		this.selection = selection;
    		structural = true; // !!! A MidiTrack, yuk
    	}
    }

    public boolean cut() {
        //        Log.debug("Cutting "+selection);
        return selection.cut();
    }

    public boolean paste() {
        return selection.paste();
    }

    /**
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private CutPasteable selection;
    
    public boolean isStructural() { return structural; }
}
