/* Generated by TooT */

package uk.org.toot.midi.sequence.edit;

import uk.org.toot.misc.UndoableCommand;

public class Move implements UndoableCommand
{
    /** @supplierCardinality 1 */
    private Moveable selection;
    private long ticks;
    private int semitones;

    public Move(Moveable selection, long ticks, int semitones)
    	throws CloneNotSupportedException {
        this.selection = (Moveable)selection.clone();
        this.ticks = ticks;
        this.semitones = semitones;
    }

    public String getName() { return "Move"; }

    public boolean execute() { selection.move(ticks, semitones); return true;}

    public boolean unexecute() { selection.move(-ticks, -semitones); return true; }

	public boolean isStructural() {
		return false;
	}
}
