/* Generated by TooT */

package uk.org.toot.midi.sequence.edit;

import uk.org.toot.midi.sequence.MidiNote;

public interface Selection extends Transposable, CutPasteable, Moveable, Copyable
{
    boolean contains(MidiNote note);

    int size();
}
