/* Generated by TooT */

package uk.org.toot.midi.sequence.edit;

import uk.org.toot.misc.UndoableCommand;

public class Transpose implements UndoableCommand
{
	private boolean structural = false;
	
    public Transpose(Transposable selection, int semitones) {
	    //throws CloneNotSupportedException {
    	try {
    		this.selection = (Transposable)selection.clone();
    	} catch ( CloneNotSupportedException cnse ) {
    		this.selection = selection;
    		structural = true; // !!! a MidiTrack?, yuk !!! !!!
    	}
        this.semitones = semitones;
    }

    public String getName() { return "Tranpose"; }

    public boolean execute() { return selection.transpose(semitones); }

    public boolean unexecute() { return selection.transpose(-semitones); }

    /** @supplierCardinality 1 */
    private Transposable selection;
    private int semitones;
    
	public boolean isStructural() {	return structural; }
}
